[package]
name = "winansi"
version = "0.1.0"
authors = ["Luke I. Wilson <thelukaswils@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "*", features = ["consoleapi", "processenv"] }
